# Generated by Django 6.0 on 2026-02-12 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='is_active',
        ),
        migrations.AddField(
            model_name='accounts',
            name='following',
            field=models.ManyToManyField(related_name='connection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts',
            name='timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
