# Generated by Django 6.0 on 2026-02-12 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_remove_accounts_is_active_accounts_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='connection', to=settings.AUTH_USER_MODEL),
        ),
    ]
