# Generated by Django 6.0.2 on 2026-02-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0007_alter_accounts_id_alter_devices_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Devices",
        ),
    ]
