# Generated by Django 6.0.2 on 2026-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0008_delete_devices"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
