# Generated by Django 6.0.2 on 2026-02-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0009_accounts_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounts",
            name="is_active",
        ),
    ]
